apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: network
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  sources:
    - chart: k8s-gateway
      repoURL: https://ori-edge.github.io/k8s_gateway
      targetRevision: 2.4.0
      helm:
        valueFiles:
          - $values/k8s/manifests/external-dns/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
