apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: network
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.3
      helm:
        valueFiles:
          - $values/k8s/apps/metallb/values.yaml
    - repoURL: https://github.com/LiquidPL/homelab.git
      targetRevision: master
      path: k8s/apps/metallb/resources
      ref: values
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
