apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lan-dns
  namespace: argocd
  labels:
    name: lan-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: network
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  sources:
    - repoURL: https://github.com/LiquidPL/homelab.git
      path: k8s/charts/unbound
      targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
