hypervisors:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local
      nodes:
        # - hostname: cluster-dev-control-plane-1
        #   cores: 2
        #   memory: 4096
        #   disk_size: 80G
        # - hostname: cluster-dev-agent-1
        #   cores: 4
        #   memory: 8192
        #   disk_size: 80G
        - hostname: cluster-dev-control-plane-1
        - hostname: cluster-dev-control-plane-2
        - hostname: cluster-dev-control-plane-3
        - hostname: cluster-dev-agent-1
        - hostname: cluster-dev-agent-2
        - hostname: cluster-dev-agent-3

control_planes:
  vars:
    k3s_control_node: true
    k3s_server:
      secrets-encryption: true
      disable-network-policy: true
      flannel-backend: 'none'
      disable:
        - traefik
        - servicelb
      kubelet-arg:
        - 'resolv-conf=/run/systemd/resolve/resolv.conf'
        - 'authentication-token-webhook=true'
        - 'authorization-mode=Webhook'
  hosts:
    cluster-dev-control-plane-1:
    cluster-dev-control-plane-2:
    cluster-dev-control-plane-3:

agents:
  vars:
    k3s_agent:
      kubelet-arg:
        - 'resolv-conf=/run/systemd/resolve/resolv.conf'
        - 'authentication-token-webhook=true'
        - 'authorization-mode=Webhook'
  hosts:
    cluster-dev-agent-1:
    cluster-dev-agent-2:
    cluster-dev-agent-3:

nodes:
  vars:
    k3s_use_unsupported_config: true
    k3s_etcd_datastore: true
    k3s_registration_address: cluster-dev-control-plane-1
  children:
    control_planes:
    agents:
