hypervisors:
  hosts:
    proxmox.hs.liquid.sh:
      ansible_host: 10.10.0.50
      ansible_user: root
      node_name: proxmox
      storage: local-zfs
      nodes:
        - hostname: homelab-control-plane-1
          cores: 2
          memory: 4096
          disk_size: 15G
          mac: 'bc:24:11:62:c3:81'
        - hostname: homelab-control-plane-3
          cores: 2
          memory: 4096
          disk_size: 15G
          mac: 'bc:24:11:66:26:e6'
        - hostname: homelab-agent-1
          cores: 4
          memory: 10240
          disk_size: 80G
          mac: 'bc:24:11:e1:29:cf'
    proxmox2.hs.liquid.sh:
      ansible_host: 10.10.0.51
      ansible_user: root
      node_name: proxmox2
      storage: local
      nodes:
        - hostname: homelab-control-plane-2
          cores: 3
          memory: 2560
          disk_size: 20G
          mac: 'bc:24:11:1d:73:27'
        - hostname: homelab-agent-2
          cores: 3
          memory: 3584
          disk_size: 80G
          mac: 'bc:24:11:ac:f7:57'


control_planes:
  vars:
    k3s_control_node: true
    k3s_server:
      node-taint: node-role.kubernetes.io/control-plane:NoSchedule
      secrets-encryption: true
      disable-network-policy: true
      flannel-backend: 'none'
      disable:
        - traefik
        - servicelb
        - metrics-server
      kubelet-arg:
        - 'kube-reserved=cpu=250m,memory=1500Mi,ephemeral-storage=1Gi'
        - 'system-reserved=cpu=250m,memory=300Mi'
        - 'resolv-conf=/run/systemd/resolve/resolv.conf'
        - 'authentication-token-webhook=true'
        - 'authorization-mode=Webhook'
  hosts:
    homelab-control-plane-1:
    homelab-control-plane-2:
    homelab-control-plane-3:

agents:
  vars:
    k3s_agent:
      kubelet-arg:
        - 'kube_reserved=cpu=50m,memory=300Mi,ephemeral-storage=1Gi'
        - 'system_reserved=cpu=250m,memory=300Mi'
        - 'resolv-conf=/run/systemd/resolve/resolv.conf'
        - 'authentication-token-webhook=true'
        - 'authorization-mode=Webhook'
  hosts:
    homelab-agent-1:
    homelab-agent-2:
      k3s_agent:
        node-taint: 'cpu-class=low-performance:NoSchedule' # raspberry pi node is considerably slower than the x86_64 node

nodes:
  vars:
    k3s_etcd_datastore: true
    k3s_registration_address: homelab-control-plane-1
  children:
    control_planes:
    agents:
