apiVersion: v1
kind: Service
metadata:
  name: frigate-rtsp
  namespace: apps
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate
  annotations:
    metallb.universe.tf/allow-shared-ip: 'key-to-share-192.168.1.20'
spec:
  type: LoadBalancer
  ports:
    - name: rtsp
      port: 8554
      targetPort: rtsp
      protocol: TCP
  selector:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate
