apiVersion: v1
kind: Service
metadata:
  name: frigate-webrtc
  namespace: apps
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate
  annotations:
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  ports:
    - name: webrtc
      port: 8555
      targetPort: webrtc
      protocol: UDP
  selector:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate
