- name: Undefine VM
  community.libvirt.virt:
    command: undefine
    name: '{{ item.hostname }}'
    force: true
    uri: qemu:///system
  loop: '{{ nodes }}'

- name: Get libvirt storage pools
  community.libvirt.virt_pool:
    command: facts

- name: Remove VM image
  ansible.builtin.command: virsh -c qemu:///system vol-delete --pool default {{ item.hostname }}.qcow2
  args:
    removes: '{{ ansible_libvirt_pools.default.path }}/{{ item.hostname }}.qcow2'
  loop: '{{ nodes }}'
  become: true

- name: Cleanup butane config directory
  ansible.builtin.file:
    path: /var/lib/libvirt/butane
    state: absent
  become: true
