longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

longhornDriver:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

defaultSettings:
  taintToleration: node-role.kubernetes.io/control-plane:NoSchedule
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: 2
  backupTarget: nfs://truenas.hs.liquid.sh:/mnt/pool/longhorn

persistence:
  defaultClassReplicaCount: 2

ingress:
  enabled: true
  host: longhorn.hs.liquid.sh
  tls: true
  tlsSecret: tls-longhorn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
