apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  encryptedData:
    api-token: AgCXrVU/rt1hQlo59F0WP3JmAcyirb77SrpKzq7M5lcUvFp+VmSu1NOgHRM9s4umX46k9ZejYRTnZePVwF3MxBT3UR/N2OVS15IVjNOM0i9gp+zimo6/oAH9oWg792eiwXvV3VFPBUqr7VRlPl+2Xyt/GwCVbF7MmiJJLUyzPJjV+P9TGUalaWAA5FR9irz5b6FkH+rpA5Xq0LivshPo53VO9Zflp/2Hbt8aCyeWuGhODYezV2WIbpY4C1apnPGmLHFRfDn74b/g+mTzggpeEJvcGRMjkLWBwwsbP6Ms7tX1avio1m8XAd6BG1CwY6llBkmdpyOyJf9o0sH9rnW5QKIHCijGsKnUZyYrEbwFsQc/1Gl4BAQp1aPH/yNpSKk1ZUkAENObdXGkarRinSJagj+mei6lRWfuxWEI1glV88VdzYMuByngpBemoAcRTwX5iXNKY6ZN46dBazBGxKgqFEM4aupagpaxOs3ZvQ7QZ5QVGmVUOlguwhVRmkKFM1laCjPiJkJfawbyq28V2dPyaUnkZ/Q8k9/v0WyzWIR/S5MT0LC0LS6mSpiggV69NIJVV9AufuubIWor26kduyIjdywGwtKl7a3QJuPv5WtLbmPTbwipGVI1ECeRmnVHvFURS3QF4mOLeb6wqCevP0X/t1rG4TUCjwJ9mFt5HZ50BkeBfvJaeHG12O594Hte6ezzlutzgFWPaUqXFXEXy39cxklDdI7I6aUBm3SqwnwZ5C2j8SBwvbBzchFa
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "100"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
