- name: Check if the image is downloaded
  ansible.builtin.stat:
    path: '{{ image_tmp_path }}'
  register: image

- name: Download Fedora CoreOS image
  when: not image.stat.exists
  block:
    - name: Download image (amd64)
      ansible.builtin.get_url:
        url: '{{ fcos_downloads.amd64.url }}'
        dest: '{{ image_tmp_path }}.xz'
        checksum: '{{ fcos_downloads.amd64.checksum }}'
        mode: '0664'
      when: ansible_architecture == "x86_64"

    - name: Download image (aarch64)
      ansible.builtin.get_url:
        url: '{{ fcos_downloads.aarch64.url }}'
        dest: '{{ image_tmp_path }}.xz'
        checksum: '{{ fcos_downloads.aarch64.checksum }}'
        mode: '0664'
      when:
        - ( ansible_facts.architecture is search("arm") and
            ansible_facts.userspace_bits == "64" ) or
          ansible_facts.architecture is search("aarch64")

    - name: Extract image
      ansible.builtin.command: 'xz --decompress {{ image_tmp_path }}.xz'
      args:
        creates: '{{ image_tmp_path }}'
