apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-upload
  labels:
    immich-volume: upload
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    server: 192.168.1.51
    path: "/mnt/pool/immich/upload"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload
spec:
  storageClassName: ''
  selector:
    matchLabels:
      immich-volume: upload
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-external
  labels:
    immich-volume: external
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    server: 192.168.1.51
    path: "/mnt/pool/immich/external"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external
spec:
  storageClassName: ''
  selector:
    matchLabels:
      immich-volume: external
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
