apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
  labels:
    name: frigate
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: apps
  sources:
    - chart: frigate
      repoURL: https://blakeblackshear.github.io/blakeshome-charts/
      targetRevision: 7.5.0
      helm:
        valueFiles:
           - $values/k8s/apps/frigate/values.yaml
    - repoURL: https://github.com/LiquidPL/homelab.git
      targetRevision: master
      path: k8s/apps/frigate/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
