apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  encryptedData:
    api-token: AgCv0wGm3zHr8HNjtaaNgrdRF8X2T4zpEy5qRcJWen83WeHbEYZUZcQbDS5bXe7EkuzfS/ZkgNpCLBRt7Xp2EdP8FESMWcqLboQ6y4DLT2yTfItVtqGu7wJwITNKz7bZI7E7PPI58yIeZtqohQ13Vqu3c4h1xM3GOxMX4TxHOQg95Sxn2kNJD4ojgz7X8Sv6TFEfl0HpdCuw3hV8Fz741NsCTZyuxjflf4ynR7hbHgE8LAmc2ZXcyy+igA+YORJ1uSii88F5t8ualFz81wAl7zvOf6VuEvZWEjRYJBJe4JgMRhAb64kLBHer1WoFEuxkQHgfALJpXbyHEdhQphciOoxXUEZ6P+GAM6C1X9VITRbsLMI3frq4URW3h078J74YAIuY5QuzSDG1FdhhHo6VtFhZhcZ7G+nZI4rbdioIyhtJ6Y6mw4zd5GliGVqGUAusIn/GBkFmA9ND7P5vjwbM3f0MgeFfQyBVlHFGVlS9Uk4K5VHdAiDA3d2po93FcdbuJ6TQ10yU+ZOwCX3Be8mLMWRMepVpNuxz7pEtjkzyEDCglT1cETIi0Rn8KEVwvV5/dBsEe7AMQdOjmBLvksGLKkg3m8XxQDgcvs1S30D02buimC77O2pPl3t4BHhnaaG23cjEF5WafG+W3udH2ikS77IfdfNACFiqtCoGJIvKinlx5Wg7OCFddtH9oGcii8oKTDX1j/qy7A+qD7RVqOQzCoSvNn0lg7CkxDEAEVc1BECaOvtJm4e4nagR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
