apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: truenas
  namespace: argocd
  labels:
    name: truenas
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  project: core
  source:
    repoURL: https://github.com/LiquidPL/homelab.git
    targetRevision: master
    path: k8s/apps/truenas
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
