apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-nfs
  namespace: argocd
  labels:
    name: zfs-nfs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  sources:
    - repoURL: https://github.com/LiquidPL/homelab.git
      targetRevision: master
      path: k8s/manifests/zfs-nfs/resources
      ref: values
    - chart: democratic-csi
      repoURL: https://democratic-csi.github.io/charts
      targetRevision: 0.14.6
      helm:
        valueFiles:
          - $values/k8s/manifests/zfs-nfs/values.yaml
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
