apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zfs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/LiquidPL/homelab.git
        revision: master
        directories:
          - path: k8s/manifests/zfs/*
          - path: k8s/manifests/zfs/resources
            exclude: true
  template:
    metadata:
      name: zfs-{{ .path.basename }}
      namespace: argocd
      labels:
        name: zfs-{{ .path.basename }}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: core
      destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
      sources:
        - repoURL: https://github.com/LiquidPL/homelab.git
          targetRevision: master
          path: k8s/manifests/zfs/resources
          ref: values
        - chart: democratic-csi
          repoURL: https://democratic-csi.github.io/charts
          targetRevision: 0.14.6
          helm:
            valueFiles:
              - $values/k8s/manifests/zfs/values.yaml
              - $values/k8s/manifests/zfs/{{ .path.basename }}/values.yaml
      syncPolicy:
        automated:
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 3
        syncOptions:
          - CreateNamespace=true
