apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas-1
  labels:
    kubernetes.io/service-name: truenas
    endpointslice.kubernetes.io/managed-by: admin
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - 192.168.1.51
    conditions:
      ready: true
---
# TODO: remove this once traefik starts using EndpointSlices
# see: https://github.com/traefik/traefik/issues/10638
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
subsets:
  - addresses:
      - ip: 192.168.1.51
    ports:
      - name: http
        port: 80
        protocol: TCP
