- name: Check if the image is downloaded
  ansible.builtin.stat:
    path: /tmp/fcos.qcow2
  register: image

- name: Download Fedora CoreOS image
  when: not image.stat.exists
  block:
    - name: Download image (amd64)
      ansible.builtin.get_url:
        url: '{{ fcos_downloads.amd64.url }}'
        dest: /tmp/fcos.qcow2.xz
        checksum: '{{ fcos_downloads.amd64.checksum }}'
        mode: '0664'
      when: ansible_architecture == "x86_64"

    - name: Download image (aarch64)
      ansible.builtin.get_url:
        url: '{{ fcos_downloads.aarch64.url }}'
        dest: /tmp/fcos.qcow2.xz
        checksum: '{{ fcos_downloads.aarch64.checksum }}'
        mode: '0664'
      when:
        - ( ansible_facts.architecture is search("arm") and
            ansible_facts.userspace_bits == "64" ) or
          ansible_facts.architecture is search("aarch64")

    - name: Extract image
      ansible.builtin.command: xz --decompress /tmp/fcos.qcow2.xz
      args:
        creates: /tmp/fcos.qcow2

- name: Import image to the libvirt storage pool
  ansible.builtin.shell: |
    virsh -c qemu:///system vol-create-as default fcos.qcow2 0
    virsh -c qemu:///system vol-upload --pool default fcos.qcow2 /tmp/fcos.qcow2
  args:
    creates: '{{ ansible_libvirt_pools.default.path }}/fcos.qcow2'
