apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exdns
  namespace: argocd
  labels:
    name: exdns
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  sources:
    - chart: k8s-gateway
      repoURL: https://ori-edge.github.io/k8s_gateway
      targetRevision: 2.4.0
      helm:
        valueFiles:
          - $values/k8s/k8s_gateway/values.yaml
    - repoURL: https://github.com/LiquidPL/homelab.git
      targetRevision: master
      ref: values
