apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    name: traefik
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 28.0.0
      helm:
        valueFiles:
          - $values/k8s/traefik/values.yaml
    - repoURL: https://github.com/LiquidPL/homelab.git
      targetRevision: master
      path: k8s/traefik
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
