apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lan-dns
  namespace: argocd
  labels:
    name: lan-dns
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  sources:
    - repoURL: https://github.com/LiquidPL/homelab.git
      path: k8s/unbound
      targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
