apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgB+wP82EMWYN0tVs19G2f5Hidae5T5RKYtZiX9xfoLat4H0DV68iBk/ETQCL7oCNGYyO+ysSdFcoBNGD7OPlapyYJdGP8862Sw9Rgs7pb7jlcTwvOeirsnUHfp0P6i4sJSy6uYedc6N2N+fsO3UC14VRX+LuclyL+PcgJmEH2dbrjP2k72DbyMhG3U4t7RZ33dK2+7qly5BC+TjQ8bHtIUYX8Fuoip+KYvWIhWyjXimK0+NCj7H5Wyu3KabucfC9kmRVeDDfIjGbmSY/0lAutI8/ht+TiYl5fL9K5ViD/fZKrkRgDAHdJ9x+tkwqPZ39q2IphMe20Gb7glr5t4CWZYNphGgGjSAd9z1l2i7RedWheIlkLPA2t8ucN2LSxoqQB9Q5NW5GSr95Gv5tjQpSL7MQ+Q2bDsZmHa14lFo5pCnDE+idx9s2/ufMgdaXllmJOHqoNG6sZcaVycmQDnbQoAWOiATjGsR+BvW4GsBniBYxjof/SMe3o0ZlP4s85S1Y3kY76GD9/xZnaYv5uL5E+4rLwszR3MRPV0S87AV8VKFepi0UW+k4HbcVacXEtLZoNNGKggx6j4Jtwa8ZshH9JyKAAO4SKGGmBd7pFA499kNQgPvnWQs6kkYvWnSCQPMp3N88B89OoF7mzMqtPFAo2UlQFAiPk561+QHeysf7uhDDX2/IFOfSYmMUr+AXyttThGf0LokkYp/NJW2X/WPMxsVjg==
    client_secret: AgAlr6gU5Uunzr2I6S+SsIZGBB7/RWW6wqOxUTmU/SSuFiLf1qxtabPY8lTGxhyAprTUlUUpLpmEJviCZWbgRTUlESCbPDYX+GP6V/Wtu91XLjLm2EQ7G0My+dxDyCbKY7t10tOveEuFdAtuJ7zh6RDFl+FwflRnXxayg8pGWRUEWfsmlvXMdwB2RjusOV9pIOASD/Gu5aMq4J5HJoSDOt70NZwk3aOWcFhZFa+S/QVpCgwRhMGsdOyWsYv1UxLInrqXT5zNllJvRNs3XxFDSIkFLWmwrnNud/QIXo7W5FToPhUsl7DNfVUMlhSS3bHW4w44EP02r8FSiYWoD4jDvo/Nz1Ixt3Pr8KxUISzd2rliRVuFxUOZlW/aQZM8HSJFE9/p2yRadgEr1mx6FGgHbG9Es9MBjMLQ/m5Ilr1rmERrgNNXm61sYkIKSTUGXm7zrTfXCurKX6a3DmtjW6dKuH16lZeiKfoA3XTanjdjCvmVil5c5emQqz9nTa72JiOFot8v/xF+AVgGaQ25HwhOLEIplH9SSH8R9fUr2gydKi60eYzDCtYf0WlsQy62hcWqynRfE119g6jutPRAzWDgD5TF5pCq9EKGU4+3RARagmjH+8qE2gLrl+uH/7+4/RHlhD3aLHt/GP5sMUkqVEpKnOvjeBQjjHFM7AML/2zDp/p7lIOQ9RuRFsJQwkbqrUuYXW9ki176iw8Z3IIu7D6q3NnaVVOWjkJRLqdxq6XmcqXxvaAegVc+TpB0Ect+zOPjShMWB1RB7fHzqi+WBuxPD2o=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
