apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: truenas-api-key
  namespace: democratic-csi
spec:
  encryptedData:
    apiKey: AgAAfzFLKEW2EO4MRvYkhy1N874Gh0Zx7WOK9XvaoADEpBWhiG07p1zvishLQFJNwlTNzluKw3Zj540eFYo2VDTLg02AI3/2R15AF5YNHJJCMNhWAbX30+CJnVZZcgvA41k98cbIZaS2kjLFgqXOVhlq1YsO9p7i38FwunxICx/i6IjtaiuYWwEPfN98XIzLs/u082ae05wfNluo4w9SvyxNzmpQRZ9u0Hs9WTSkJ1m0N9G+ns13qAl/PGsKPd8fPUJ5XV+MZa+7h0DMd28hcf2Tzi3hMrJwfkNNbfGOixqjWjPXkE9Z9xP5LoOc8NkM6gLwuabeZ5eJkb2uvgV1ViUj9w88hs/Le+By0TaSFML9utrB9rk8/pwN7Ft7peH1/pMxEPGs4iEdDznVCsmGBJm65jgD9KQECxw/RAg1JijBXSj7qUcXemm8oWS/2tJK+pjvdezXlvhNwCL+w/EL8AIVITcW21OW0ARwDab8rlPLnTSteORuJkzGs0eHp0JJWqAKAHJlzzEUddVTPR6r9Ctx/bNuD1sP9GmzmWI4J4xoevlvo4EsQ7JP+wAaxeb7X3y+UC7BaqPAhzom50efpzHeoCv0/PaXzpjoGLLsfOztTsVSSPC8LqLq7KLmIFLqFwpvmXb3gF9fFMbkLUgdcI6vANdIP+nn1+GRxHYP00VYCLL2pHHp2dnZXSIMvpIyz6FnYkiV2WKnuTpzCBO2C7Xcg5VkhQF9QbAyYEJvyf5fNOIW9oKVhnIv2PnYkcJudvWPrWV6utHeMuS3UZAARPZHykY=
  template:
    metadata:
      creationTimestamp: null
      name: truenas-api-key
      namespace: democratic-csi
    type: Opaque
