config: |
  # TODO: configure auth and tls once the helm chart is updated to support 0.14
  auth:
    enabled: false
  tls:
    enabled: false
  mqtt:
    enabled: true
    host: 10.10.0.200
    user: '{FRIGATE_MQTT_USER}'
    password: '{FRIGATE_MQTT_PASSWORD}'
  detectors:
    ov:
      type: openvino
      device: GPU
  model:
    width: 300
    height: 300
    input_tensor: nhwc
    input_pixel_format: bgr
    path: /openvino-model/ssdlite_mobilenet_v2.xml
    labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  go2rtc:
    streams:
      driveway:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.10.10.11:554/cam/realmonitor?channel=1&subtype=0
      driveway_sub:
        - 'ffmpeg:driveway#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi'
      backyard:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.10.10.10:554/cam/realmonitor?channel=1&subtype=0
      backyard_sub:
        - 'ffmpeg:backyard#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi'
    webrtc:
      candidates:
        - 10.10.100.254:8555
        - 100.118.30.9:8555
        - stun:8555
      ice_servers:
        - urls: [stun:stun.l.google.com:19302]
  ffmpeg:
    hwaccel_args: preset-intel-qsv-h264
  cameras:
    driveway:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/driveway
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/driveway_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      objects:
        track:
          - person
          - car
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        events:
          retain:
            default: 14
            mode: active_objects
    backyard:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/backyard
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/backyard_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        events:
          retain:
            default: 14
            mode: active_objects
image:
  tag: 0.14.1
persistence:
  media:
    enabled: true
    size: 650Gi
    storageClass: nfs-csi
    skipuninstall: true
  config:
    enabled: true
    size: 512Mi
    storageClass: longhorn
    skipuninstall: true
securityContext:
  capabilities:
    add:
      - PERFMON
resources:
  limits:
    gpu.intel.com/i915: 100
envFromSecrets:
  - frigate-secrets
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: frigate.hs.liquid.sh
      paths: ["/"]
  tls:
    - hosts:
        - frigate.hs.liquid.sh
      secretName: tls-frigate-ingress
