config: |
  mqtt:
    enabled: true
    host: 192.168.1.200
    user: '{FRIGATE_MQTT_USER}'
    password: '{FRIGATE_MQTT_PASSWORD}'
  detectors:
    ov:
      type: openvino
      device: AUTO
      model:
        path: /openvino-model/ssdlite_mobilenet_v2.xml
  model:
    width: 300
    height: 300
    input_tensor: nhwc
    input_pixel_format: bgr
    labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  go2rtc:
    streams:
      driveway:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.211:554/cam/realmonitor?channel=1&subtype=0
      driveway_sub:
        - 'ffmpeg:driveway#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi'
      backyard:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.210:554/cam/realmonitor?channel=1&subtype=0
      backyard_sub:
        - 'ffmpeg:backyard#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi'
    webrtc:
      candidates:
        - 192.168.1.21:8555
        - 100.118.30.9:8555
        - stun:8555
      ice_servers:
        - urls: [stun:stun.l.google.com:19302]
  ffmpeg:
    hwaccel_args: preset-intel-qsv-h264
  cameras:
    driveway:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/driveway
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/driveway_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      motion:
        mask:
          - 1240,30,1238,54,960,56,961,27
          - 0,581,93,441,0,353
          - 1280,359,1280,0,1108,0,1053,21,994,60,1005,117,1003,180
          - 605,336,560,282,516,327,538,436
          - 478,257,512,197,462,195,458,256,455,301
      zones:
        actual_driveway:
          coordinates: 753,141,726,159,763,181,804,199,704,197,580,197,483,192,439,151,399,137
          objects:
            - car
        road:
          coordinates: 462,127,620,129,827,136,1058,162,1280,187,1280,152,1128,119,987,89,869,68,639,41,533,40,451,38,303,45,127,60,130,152,307,139
      objects:
        track:
          - person
          - car
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        events:
          required_zones:
            - actual_driveway
          retain:
            default: 14
            mode: active_objects
    backyard:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/backyard
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/backyard_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      motion:
        mask:
          - 963,54,1236,55,1237,32,963,30
          - 928,0,1280,0,1280,117
          - 377,231,377,304,333,304,331,229
          - 270,188,395,190,382,224,244,229
          - 0,362,36,343,56,301,81,278,110,292,149,280,139,247,97,195,67,155,86,134,108,104,156,118,165,96,153,68,182,54,165,0,0,0
          - 0,452,0,613,70,601
          - 410,61,388,0,454,0,446,33,435,74,414,105
          - 1280,197,1152,174,773,143,390,129,0,127,0,157,99,160,408,165,611,171,1081,204,1280,225
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        events:
          retain:
            default: 14
            mode: active_objects
image:
  tag: 0.13.2
persistence:
  media:
    enabled: true
    size: 650Gi
    storageClass: nfs-csi
    skipuninstall: true
  config:
    enabled: true
    size: 512Mi
    storageClass: longhorn
    skipuninstall: true
securityContext:
  capabilities:
    add:
      - PERFMON
resources:
  limits:
    gpu.intel.com/i915: 100
envFromSecrets:
  - frigate-secrets
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: frigate.hs.liquid.sh
      paths: ["/"]
  tls:
    - hosts:
        - frigate.hs.liquid.sh
      secretName: tls-frigate-ingress
